import type { Metadata } from "next";
import {Poppins } from "next/font/google";
// import "../../app/globals.css";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "Carrick groupe",
  description: "Generated by Mr Développeur",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${poppins.style} ${poppins.className}`}>
      <body
        className={`${poppins.variable} ${poppins.style} ${poppins.className} antialiased font-light text-[16px]`}
      >
        {children}
      </body>
    </html>
  );
}
