export const projects = [
  {
    id: "01",
    title: "Complexe résidentiel — Abidjan",
    category: "Construction",
    status: "Livré",
    desc: "Construction d'un immeuble R+4 de 24 appartements, avec parking souterrain et espace paysager.",
    // image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    image: "/realise/001.jpeg",
    tags: ["Résidentiel", "Clés en main", "Terrassement"],
    accent: "#68277f",
  },
  {
    id: "02",
    title: "Construction — Immeuble commercial",
    category: "Construction",
    status: "Livré",
    desc: "Réalisation d'un immeuble commercial incluant l'installation de 120 m² de fenêtres coulissantes à haute performance thermique, assurant confort, luminosité et efficacité énergétique.",
    image: "/realise/002.jpeg",
    tags: ["Construction", "Fenêtres", "Performance énergétique"],
    accent: "#7EB8D4",
  },
//   {
//     id: "03",
//     title: "Structuration d'investissement SCPI",
//     category: "Conseil",
//     status: "En cours",
//     desc: "Accompagnement d'un groupe d'investisseurs dans la structuration d'un portefeuille immobilier via crowdfunding.",
//     // image: "https://images.unsplash.com/photo-1460472178825-e5240623afd5?w=600&q=80",
//     image: "/realise/003.jpeg",
//     tags: ["Investissement", "SCPI", "Crowdfunding"],
//     accent: "#B87ED4",
//   },
  {
    id: "04",
    title: "Réhabilitation d'entrepôt industriel",
    category: "Construction",
    status: "Livré",
    desc: "Rénovation complète d'un entrepôt de 800 m² avec mise aux normes et réorganisation des flux logistiques.",
    // image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    image: "/realise/004.jpeg",
    tags: ["Réhabilitation", "Industriel", "Normes"],
    accent: "#7EC88A",
  },
  {
    id: "05",
    title: "Aménagement Intérieur Boutique",
    category: "Construction",
    status: "Livré",
    desc: "Conception et réalisation complète de l'aménagement intérieur d'un espace commercial : mobilier sur mesure en bois clair, casiers d'exposition, comptoir vitré et plancher stratifié pour un rendu moderne et chaleureux.",
    image: "/realise/05.jpeg",
    tags: ["Aménagement intérieur", "Mobilier sur mesure", "Espace commercial"],
    accent: "#7EC88A",
  },
  {
    id: "06",
    title: "Construction Espace Commercial",
    category: "Construction",
    status: "Livré",
    desc: "Réalisation d'un grand espace commercial avec faux plafond décoratif aux motifs ondulés, climatisation encastrée et finitions peinture soignées. Chantier mené avec rigueur jusqu'à la livraison.",
    image: "/realise/006.jpeg",
    tags: ["Faux plafond", "Finition intérieure", "Local commercial"],
    accent: "#7EC88A",
  },
  {
    id: "07",
    title: "Bâtiment & Jardin Paysager",
    category: "Construction",
    status: "Livré",
    desc: "Construction d'un bâtiment moderne avec façade vitrée aluminium et toiture métallique, complétée par un aménagement paysager soigné : pelouse, dalles en pierre naturelle et végétation tropicale.",
    image: "/realise/007.jpeg",
    tags: ["Façade aluminium", "Aménagement paysager", "Pelouse & pierres"],
    accent: "#7EC88A",
  },
];
